/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OrgNameLayoutImport } from './routes/$orgName/layout'
import { Route as IndexImport } from './routes/index'
import { Route as LandingIndexImport } from './routes/landing/index'
import { Route as OrgNameIndexImport } from './routes/$orgName/index'
import { Route as OrgNameDatabaseLayoutImport } from './routes/$orgName/database/layout'
import { Route as OrgNameHomeIndexImport } from './routes/$orgName/home/index'
import { Route as OrgNameDatabaseTableIdViewIndexImport } from './routes/$orgName/database/$tableId/view/index'
import { Route as OrgNameDatabaseTableIdViewViewIdImport } from './routes/$orgName/database/$tableId/view/$viewId'

// Create/Update Routes

const OrgNameLayoutRoute = OrgNameLayoutImport.update({
  id: '/$orgName',
  path: '/$orgName',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LandingIndexRoute = LandingIndexImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRoute,
} as any)

const OrgNameIndexRoute = OrgNameIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgNameLayoutRoute,
} as any)

const OrgNameDatabaseLayoutRoute = OrgNameDatabaseLayoutImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => OrgNameLayoutRoute,
} as any)

const OrgNameHomeIndexRoute = OrgNameHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => OrgNameLayoutRoute,
} as any)

const OrgNameDatabaseTableIdViewIndexRoute =
  OrgNameDatabaseTableIdViewIndexImport.update({
    id: '/$tableId/view/',
    path: '/$tableId/view/',
    getParentRoute: () => OrgNameDatabaseLayoutRoute,
  } as any)

const OrgNameDatabaseTableIdViewViewIdRoute =
  OrgNameDatabaseTableIdViewViewIdImport.update({
    id: '/$tableId/view/$viewId',
    path: '/$tableId/view/$viewId',
    getParentRoute: () => OrgNameDatabaseLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$orgName': {
      id: '/$orgName'
      path: '/$orgName'
      fullPath: '/$orgName'
      preLoaderRoute: typeof OrgNameLayoutImport
      parentRoute: typeof rootRoute
    }
    '/$orgName/database': {
      id: '/$orgName/database'
      path: '/database'
      fullPath: '/$orgName/database'
      preLoaderRoute: typeof OrgNameDatabaseLayoutImport
      parentRoute: typeof OrgNameLayoutImport
    }
    '/$orgName/': {
      id: '/$orgName/'
      path: '/'
      fullPath: '/$orgName/'
      preLoaderRoute: typeof OrgNameIndexImport
      parentRoute: typeof OrgNameLayoutImport
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingIndexImport
      parentRoute: typeof rootRoute
    }
    '/$orgName/home/': {
      id: '/$orgName/home/'
      path: '/home'
      fullPath: '/$orgName/home'
      preLoaderRoute: typeof OrgNameHomeIndexImport
      parentRoute: typeof OrgNameLayoutImport
    }
    '/$orgName/database/$tableId/view/$viewId': {
      id: '/$orgName/database/$tableId/view/$viewId'
      path: '/$tableId/view/$viewId'
      fullPath: '/$orgName/database/$tableId/view/$viewId'
      preLoaderRoute: typeof OrgNameDatabaseTableIdViewViewIdImport
      parentRoute: typeof OrgNameDatabaseLayoutImport
    }
    '/$orgName/database/$tableId/view/': {
      id: '/$orgName/database/$tableId/view/'
      path: '/$tableId/view'
      fullPath: '/$orgName/database/$tableId/view'
      preLoaderRoute: typeof OrgNameDatabaseTableIdViewIndexImport
      parentRoute: typeof OrgNameDatabaseLayoutImport
    }
  }
}

// Create and export the route tree

interface OrgNameDatabaseLayoutRouteChildren {
  OrgNameDatabaseTableIdViewViewIdRoute: typeof OrgNameDatabaseTableIdViewViewIdRoute
  OrgNameDatabaseTableIdViewIndexRoute: typeof OrgNameDatabaseTableIdViewIndexRoute
}

const OrgNameDatabaseLayoutRouteChildren: OrgNameDatabaseLayoutRouteChildren = {
  OrgNameDatabaseTableIdViewViewIdRoute: OrgNameDatabaseTableIdViewViewIdRoute,
  OrgNameDatabaseTableIdViewIndexRoute: OrgNameDatabaseTableIdViewIndexRoute,
}

const OrgNameDatabaseLayoutRouteWithChildren =
  OrgNameDatabaseLayoutRoute._addFileChildren(
    OrgNameDatabaseLayoutRouteChildren,
  )

interface OrgNameLayoutRouteChildren {
  OrgNameDatabaseLayoutRoute: typeof OrgNameDatabaseLayoutRouteWithChildren
  OrgNameIndexRoute: typeof OrgNameIndexRoute
  OrgNameHomeIndexRoute: typeof OrgNameHomeIndexRoute
}

const OrgNameLayoutRouteChildren: OrgNameLayoutRouteChildren = {
  OrgNameDatabaseLayoutRoute: OrgNameDatabaseLayoutRouteWithChildren,
  OrgNameIndexRoute: OrgNameIndexRoute,
  OrgNameHomeIndexRoute: OrgNameHomeIndexRoute,
}

const OrgNameLayoutRouteWithChildren = OrgNameLayoutRoute._addFileChildren(
  OrgNameLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgName': typeof OrgNameLayoutRouteWithChildren
  '/$orgName/database': typeof OrgNameDatabaseLayoutRouteWithChildren
  '/$orgName/': typeof OrgNameIndexRoute
  '/landing': typeof LandingIndexRoute
  '/$orgName/home': typeof OrgNameHomeIndexRoute
  '/$orgName/database/$tableId/view/$viewId': typeof OrgNameDatabaseTableIdViewViewIdRoute
  '/$orgName/database/$tableId/view': typeof OrgNameDatabaseTableIdViewIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$orgName/database': typeof OrgNameDatabaseLayoutRouteWithChildren
  '/$orgName': typeof OrgNameIndexRoute
  '/landing': typeof LandingIndexRoute
  '/$orgName/home': typeof OrgNameHomeIndexRoute
  '/$orgName/database/$tableId/view/$viewId': typeof OrgNameDatabaseTableIdViewViewIdRoute
  '/$orgName/database/$tableId/view': typeof OrgNameDatabaseTableIdViewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$orgName': typeof OrgNameLayoutRouteWithChildren
  '/$orgName/database': typeof OrgNameDatabaseLayoutRouteWithChildren
  '/$orgName/': typeof OrgNameIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/$orgName/home/': typeof OrgNameHomeIndexRoute
  '/$orgName/database/$tableId/view/$viewId': typeof OrgNameDatabaseTableIdViewViewIdRoute
  '/$orgName/database/$tableId/view/': typeof OrgNameDatabaseTableIdViewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgName'
    | '/$orgName/database'
    | '/$orgName/'
    | '/landing'
    | '/$orgName/home'
    | '/$orgName/database/$tableId/view/$viewId'
    | '/$orgName/database/$tableId/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$orgName/database'
    | '/$orgName'
    | '/landing'
    | '/$orgName/home'
    | '/$orgName/database/$tableId/view/$viewId'
    | '/$orgName/database/$tableId/view'
  id:
    | '__root__'
    | '/'
    | '/$orgName'
    | '/$orgName/database'
    | '/$orgName/'
    | '/landing/'
    | '/$orgName/home/'
    | '/$orgName/database/$tableId/view/$viewId'
    | '/$orgName/database/$tableId/view/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgNameLayoutRoute: typeof OrgNameLayoutRouteWithChildren
  LandingIndexRoute: typeof LandingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgNameLayoutRoute: OrgNameLayoutRouteWithChildren,
  LandingIndexRoute: LandingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$orgName",
        "/landing/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$orgName": {
      "filePath": "$orgName/layout.tsx",
      "children": [
        "/$orgName/database",
        "/$orgName/",
        "/$orgName/home/"
      ]
    },
    "/$orgName/database": {
      "filePath": "$orgName/database/layout.tsx",
      "parent": "/$orgName",
      "children": [
        "/$orgName/database/$tableId/view/$viewId",
        "/$orgName/database/$tableId/view/"
      ]
    },
    "/$orgName/": {
      "filePath": "$orgName/index.tsx",
      "parent": "/$orgName"
    },
    "/landing/": {
      "filePath": "landing/index.tsx"
    },
    "/$orgName/home/": {
      "filePath": "$orgName/home/index.tsx",
      "parent": "/$orgName"
    },
    "/$orgName/database/$tableId/view/$viewId": {
      "filePath": "$orgName/database/$tableId/view/$viewId.tsx",
      "parent": "/$orgName/database"
    },
    "/$orgName/database/$tableId/view/": {
      "filePath": "$orgName/database/$tableId/view/index.tsx",
      "parent": "/$orgName/database"
    }
  }
}
ROUTE_MANIFEST_END */
